modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT License"

[[mods]]
modId = "scalingdifficulty"
version = "1.0.1"
displayName = "ScalingDifficulty"
credits = "Globox"
authors = "Herobrot"
description = '''
Scale mob statistics based on time/distance traveled in the world. Port from Globox's RpgDifficulty
'''
logoFile = "assets/scalingdifficulty/icon.png"
logoBlur = false

[[mixins]]
config = "scalingdifficulty.mixins.json"

[[dependencies.scalingdifficulty]]
modId = "neoforge"
type = "required"
versionRange = "[21.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.scalingdifficulty]]
modId = "minecraft"
type = "required"
versionRange = "[1.21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.scalingdifficulty]]
modId = "cloth_config"
type = "required"
versionRange = "[15.0.0,)"
ordering = "AFTER"
side = "BOTH"